name: flutter_login_bloc
description: "Um projeto que utiliza ReqRes api para realizar login com BLoC"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  formz: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
